words_dictionary = {
    'easy': [
        "ability", "about", "above", "accept", "across", "action", "activity", "actually", "address", "adult",
        "after", "again", "agency", "agent", "agree", "ahead", "allow", "almost", "alone", "along",
        "already", "although", "always", "amount", "animal", "another", "answer", "anyone", "appear",
        "apply", "approach", "argue", "around", "arrive", "assume", "attack", "attention", "audience",
        "author", "available", "avoid", "beautiful", "because", "become", "before", "begin", "behind",
        "believe", "better", "between", "black", "board", "body", "break", "bring", "brother", "budget",
        "building", "business", "camera", "cancer", "candidate", "capital", "career", "carry", "catch",
        "cause", "center", "century", "certain", "chance", "change", "character", "charge", "choice",
        "church", "city", "claim", "class", "clear", "clearly", "college", "color", "commercial",
        "common", "company", "compare", "computer", "concern", "condition", "conference", "consider",
        "contain", "continue", "control", "country", "couple", "course", "create", "culture", "current",
        "customer", "daughter", "decide", "decision", "defense", "degree", "describe", "design", "despite",
        "detail", "determine", "develop", "difference", "different", "difficult", "direction", "discover",
        "discuss", "discussion", "disease", "doctor", "dream", "during", "early", "economic", "economy",
        "education", "effect", "effort", "election", "employee", "energy", "enjoy", "enough", "entire",
        "environment", "especially", "establish", "evening", "everything", "evidence", "example", "executive",
        "expect", "experience", "explain", "family", "famous", "father", "feeling", "figure", "finally",
        "financial", "follow", "foreign", "former", "friend", "future", "garden", "general", "generation",
        "government", "ground", "growth", "happen", "health", "hospital", "however", "hundred", "identify",
        "important", "include", "including", "increase", "indicate", "individual", "industry", "information",
        "interest", "international", "investment", "involve", "language", "lawyer", "leader", "learning",
        "letter", "likely", "listen", "machine", "magazine", "management", "manager", "marriage", "material",
        "measure", "meeting", "member", "memory", "message", "method", "middle", "might", "military",
        "million", "minute", "modern", "moment", "money", "morning", "mother", "movement", "nation",
        "natural", "nearly", "necessary", "network", "nothing", "number", "office", "officer", "operation",
        "opinion", "opportunity", "option", "organization", "outside", "painting", "parent", "participant",
        "particular", "partner", "party", "patient", "pattern", "people", "perform", "performance", "period",
        "personal", "physical", "picture", "planning", "political", "popular", "population", "position",
        "positive", "possible", "practice", "prepare", "present", "president", "pressure", "prevent",
        "private", "problem", "process", "produce", "product", "production", "professional", "professor",
        "project", "property", "protect", "provide", "public", "quality", "question", "quickly", "radio",
        "raise", "range", "rather", "reality", "realize", "really", "reason", "receive", "recognize",
        "record", "reduce", "reflect", "region", "relate", "relationship", "religious", "remember", "remove",
        "report", "represent", "require", "research", "resource", "respond", "response", "responsibility",
        "result", "return", "reveal", "school", "science", "scientist", "season", "second", "section",
        "security", "serious", "service", "several", "should", "similar", "simple", "simply", "situation",
        "society", "somebody", "someone", "something", "sometimes", "source", "special", "specific", "speech",
        "spend", "sport", "spring", "staff", "standard", "statement", "station", "strategy", "street", "student",
        "study", "subject", "successful", "suddenly", "suggest", "summer", "support", "surface", "system",
        "teacher", "technology", "television", "theory", "through", "throughout", "together", "towards",
        "training", "travel", "treatment", "trouble", "understand", "usually", "variety", "various", "victory",
        "village", "violence", "vision", "visitor", "whatever", "whether", "window", "within", "without",
        "worker", "worldwide", "yourself"
    ],
    'normal': [
        "abandon", "ability", "absence", "academy", "account", "accuse", "achieve", "acquire", "address",
        "advance", "advertise", "adviser", "affect", "against", "aircraft", "allegation", "allowance",
        "alongside", "ambition", "analysis", "announce", "anything", "apparent", "appearance", "applicant",
        "approach", "approval", "argument", "artistic", "assemble", "assess", "atmosphere", "attempt",
        "attendance", "attention", "attitude", "attraction", "authority", "automatic", "available", "balance",
        "barrier", "because", "behavior", "biological", "boundary", "broadcast", "business", "calculate",
        "campaign", "capacity", "category", "celebrate", "celebration", "ceremony", "challenge", "champion",
        "characteristic", "chemical", "circulate", "citizen", "classical", "clothing", "collapse", "colleague",
        "combination", "comfortable", "committee", "community", "companion", "complaint", "complex", "component",
        "composite", "concentrate", "concept", "concerned", "conclusion", "condition", "conference", "confidence",
        "congress", "connection", "consideration", "consistent", "construct", "consult", "container", "contemporary",
        "continuous", "contribute", "convention", "conversation", "convince", "corporation", "correspond", "creation",
        "creative", "criticism", "cultural", "currency", "currently", "customer", "decision", "decorate", "defendant",
        "defensive", "deliberate", "democracy", "department", "dependence", "deposit", "describe", "desperate",
        "determine", "difference", "difficulty", "diminish", "discipline", "discover", "discussion", "disease",
        "disguise", "disorder", "dispute", "distance", "distinct", "distinguish", "distribution", "diversity",
        "document", "domestic", "dominant", "dominate", "dramatic", "dressing", "duration", "dynamic", "economics",
        "education", "effective", "efficiency", "electric", "element", "embarrass", "emphasis", "employee",
        "encounter", "enormous", "enterprise", "entertain", "enthusiasm", "entirely", "envelope", "equation",
        "equipped", "essential", "establish", "estimate", "evaluate", "eventually", "evidence", "exchange",
        "exclude", "executive", "exercise", "exhibition", "existence", "expansion", "expectation", "experience",
        "experiment", "explosion", "exposure", "extended", "extensive", "external", "facility", "familiar",
        "fantastic", "fascinate", "feature", "festival", "financial", "flexible", "focus", "forecast", "foundation",
        "frequent", "function", "furniture", "generate", "generous", "governor", "gradually", "guarantee", "guidance",
        "handful", "headline", "healthy", "heritage", "highlight", "hospital", "identity", "illustrate", "imagination",
        "importance", "incident", "inclusion", "increase", "independence", "industry", "informal", "initial",
        "initiative", "innocent", "inquiry", "insight", "insurance", "intensity", "interest", "interview",
        "introduce", "invasion", "invisible", "involve", "isolation", "judgment", "landscape", "language",
        "laughter", "lifestyle", "limitation", "literally", "location", "maintain", "majority", "manifest",
        "manufacturer", "marketing", "marriage", "material", "measurement", "mechanism", "military", "minister",
        "minority", "mobility", "movement", "mysterious", "narrative", "national", "negotiate", "neighbour",
        "notebook", "objective", "obligation", "obstacle", "occasion", "occupation", "offensive", "official",
        "operator", "opponent", "opposite", "optimistic", "organization", "original", "outline", "overcome",
        "overseas", "ownership", "partnership", "perception", "performance", "permanent", "permission", "personality",
        "phenomenon", "philosophy", "physical", "politician", "pollution", "population", "portfolio", "portrait",
        "position", "positive", "potential", "practical", "precious", "preparation", "presence", "preserve",
        "prestigious", "principal", "probability", "procedure", "productive", "profession", "progress", "prohibit",
        "promotion", "proportion", "prospect", "protocol", "psychology", "publication", "publicity", "punishment",
        "quantity", "questionnaire", "quotation", "realistic", "recession", "reception", "recognize", "recovery",
        "reduction", "reference", "reflection", "reform", "refugee", "register", "regulate", "reinforce",
        "relationship", "relatively", "relevant", "remarkable", "repeatedly", "represent", "reputation", "requirement",
        "residence", "resistance", "resolution", "resource", "respective", "restaurant", "restructure", "revolution",
        "sacrifice", "scenario", "schedule", "scrutiny", "selection", "sensation", "sentence", "separate", "sequence",
        "settlement", "significance", "similarly", "simulation", "situation", "sociology", "solution", "sometimes",
        "sophisticated", "specifically", "spontaneous", "squeeze", "stability", "statement", "statistic", "strengthen",
        "structure", "subsequent", "substantial", "substitute", "successful", "sufficient", "supervise", "supplement",
        "suspicious", "sustainable", "symbolic", "sympathy", "synthesis", "technical", "technology", "temporary",
        "territory", "tournament", "tradition", "training", "transformation", "transition", "translate", "transport",
        "treatment", "ultimately", "undergo", "understanding", "undertake", "unexpected", "universal", "university",
        "unlikely", "unusual", "utilize", "variation", "vegetable", "venture", "versatile", "vertical", "victorious",
        "virtually", "visualize", "volunteer", "warranty", "withdraw", "workforce"
    ],
    'hard': [
        "abandonment", "abstraction", "accumulation", "adaptability", "advancement", "aggressiveness", "alternative",
        "appreciation", "articulation", "authorization", "characterization", "collaboration", "comprehension",
        "concentration", "confrontation", "configuration", "congratulations", "conservation", "consideration",
        "contribution", "correspondence", "declaration", "demonstration", "deterioration", "development",
        "discrimination", "documentation", "effectiveness", "establishment", "generalization", "illustration",
        "implementation", "improvement", "incompatibility", "independence", "inspiration", "interpretation",
        "introduction", "manipulation", "misunderstanding", "normalization", "organization", "participation",
        "perception", "persuasion", "prioritization", "probability", "publication", "recommendation", "relationship",
        "responsibility", "restructuring", "satisfaction", "simplification", "specialization", "standardization",
        "sustainability", "transformation", "transmission", "unpredictability", "verification", "vulnerability",
        "withdrawal", "accelerate", "apprehension", "assassination", "biotechnology", "characteristic",
        "complication", "constitutional", "conversational", "counterproductive", "decontamination", "definitively",
        "dissemination", "extraordinarily", "fundamental", "hypothetical", "implementation", "incompatibility",
        "interdisciplinary", "manifestation", "participatory", "phenomenological", "representation", "significance",
        "sophisticated", "specialization", "substantial", "unintentional", "vulnerability", "accommodation",
        "compromising", "establishing", "interconnected", "intervention", "misinterpretation", "overcompensate",
        "reconfiguration", "understanding", "transcendence", "experimental", "multidimensional", "transnational",
        "interdisciplinary", "misrepresentation", "incompatibility", "miscommunication", "overgeneralization",
        "interrelationship", "counterproductive", "reinforcement", "sustainability", "adaptation", "artificial",
        "catastrophic", "characteristic", "circumstantial", "collaboration", "compartmentalize", "contemplation",
        "contextualization", "differentiation", "disproportionate", "dissemination", "distinguishable",
        "distraction", "elaboration", "entitlement", "exaggeration", "exploitation", "inconvenience", "integration",
        "interconnectedness", "interpretative", "justification", "legitimacy", "legislation", "manipulative",
        "metaphorical", "overcomplication", "participatory", "personalization", "politicization", "questionable",
        "reconciliation", "redistribution", "reexamination", "rehabilitation", "representational", "representation",
        "subordination", "surveillance", "transformative", "understanding", "vulnerability", "assertiveness"
    ]
}
